-- Canonical schema lives in the OrisTrade project:
--   OrisTrade-Journal/supabase/CEDARCLAY_PREORDERS.sql
--   OrisTrade-Journal/supabase/CEDARCLAY_PREORDERS_STATUSES.sql  (statuses + customer edit)
--
-- Admin UI: https://journal.oristrade.com/admin/cedarclay-orders
-- Customer My Orders: https://cedarclaylife.com/orders
